services:
  myurls:
    image: xiao6666/myurls:latest
    environment:
      - MYURLS_DOMAIN=s.example.com  #你的域名
      - MYURLS_PROTO=https
      - REDIS_IP=redis  #你的其他服务器部署了rides的话可以换成对应服务器ip
      - REDIS_PORT=6379
      - REDIS_PASSWORD= #有就填，没有就空着
    volumes:
      - ./data/myurls/logs:/app/logs    
    ports:
      - "8080:8080"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:latest
    volumes:
      - ./data/redis:/data
    restart: always
